#!/bin/sh

rpm2cpio ./ms-scx-1.0.0-32074.i386.rpm | cpio -idmv
cp -f ./libSCXCoreProviderModule.so /opt/xplatproviders/lib/
cp -R ./root#scx/ /opt/openpegasus/repository/
ln -s /opt/xplatproviders/lib/libSCXCoreProviderModule.so /opt/openpegasus/providers/
printf '%s\n' '/opt/xplatproviders/lib' >> /etc/ld.so.conf.d/xs-cim-cmpi.conf
/sbin/ldconfig
/opt/xensource/packages/files/ms-scx/register-namespaces.sh
/sbin/service openpegasus restart
